#include <u.h>
#include <libc.h>
#include <draw.h>
#include <bio.h>
#include "view.h"
#include "dat.h"

/*
 * Coastline data
 *
 * coast.dat is generated by mkcoast from a Natural Earth
 * GeoJSON coastline file.  Format: one polyline per block,
 * introduced by "> N" giving the point count, followed by N
 * lines of "lat lon".  Comments and blank lines are ignored.
 *
 * The file is searched for in, in order:
 *	$coastfile (if set via coastfile())
 *	./coast.dat
 *	/lib/radio/coast.dat
 *
 * If no file is found, a coarse built-in outline is used so
 * the globe still shows something recognizable.
 */

Coastline *coasts;
int ncoast;

static char *coastpath;

/* tiny built-in fallback: rough continent blobs */
static Geo fb_africa[] = {
	{35,0},{32,25},{12,43},{-34,20},{-34,18},{5,-5},{15,-17},{35,-6},{35,0},
};
static Geo fb_eurasia[] = {
	{36,-6},{45,5},{60,10},{70,30},{65,60},{70,90},{70,140},{55,140},
	{40,120},{20,105},{8,77},{25,60},{40,50},{36,-6},
};
static Geo fb_namerica[] = {
	{8,-80},{25,-80},{45,-65},{60,-65},{72,-95},{70,-130},{55,-130},
	{33,-117},{18,-105},{8,-80},
};
static Geo fb_samerica[] = {
	{10,-72},{0,-50},{-23,-44},{-40,-62},{-55,-68},{-40,-73},{-18,-70},
	{0,-80},{10,-72},
};
static Geo fb_australia[] = {
	{-11,132},{-20,148},{-38,146},{-35,118},{-20,114},{-11,132},
};

static struct {
	Geo *pts;
	int npts;
} fallback[] = {
	{fb_africa, nelem(fb_africa)},
	{fb_eurasia, nelem(fb_eurasia)},
	{fb_namerica, nelem(fb_namerica)},
	{fb_samerica, nelem(fb_samerica)},
	{fb_australia, nelem(fb_australia)},
};

void
coastfile(char *path)
{
	coastpath = path;
}

static void
usefallback(void)
{
	int i;

	ncoast = nelem(fallback);
	coasts = malloc(ncoast * sizeof(Coastline));
	if(coasts == nil)
		sysfatal("malloc: %r");
	for(i = 0; i < ncoast; i++){
		coasts[i].pts = fallback[i].pts;
		coasts[i].npts = fallback[i].npts;
	}
}

static int
loadfile(char *path)
{
	Biobuf *b;
	char *ln, *f[2];
	int cap, np, want, nf;
	Coastline *c;
	Geo *pts;

	b = Bopen(path, OREAD);
	if(b == nil)
		return -1;

	coasts = nil;
	ncoast = 0;
	cap = 0;
	c = nil;
	pts = nil;
	np = 0;
	want = 0;

	while((ln = Brdline(b, '\n')) != nil){
		ln[Blinelen(b)-1] = 0;
		ln += strspn(ln, " \t");
		if(*ln == '#' || *ln == 0)
			continue;

		if(*ln == '>'){
			/* finish previous polyline */
			if(c != nil)
				c->npts = np;

			ln++;
			want = atoi(ln);
			if(want < 2){
				c = nil;
				pts = nil;
				np = 0;
				continue;
			}
			if(ncoast >= cap){
				cap = cap ? cap*2 : 256;
				coasts = realloc(coasts, cap*sizeof(Coastline));
				if(coasts == nil)
					sysfatal("realloc: %r");
			}
			pts = malloc(want * sizeof(Geo));
			if(pts == nil)
				sysfatal("malloc: %r");
			c = &coasts[ncoast++];
			c->pts = pts;
			c->npts = 0;
			np = 0;
			continue;
		}

		/* a "lat lon" coordinate line */
		if(c == nil || np >= want)
			continue;
		nf = tokenize(ln, f, 2);
		if(nf != 2)
			continue;
		pts[np].lat = atof(f[0]);
		pts[np].lon = atof(f[1]);
		np++;
	}
	if(c != nil)
		c->npts = np;

	Bterm(b);

	if(ncoast == 0)
		return -1;
	return 0;
}

/*
 * Compute the bounding cap for one already-vectorized coastline: a
 * center direction and the cosine of the half-angle of the smallest
 * cone around that center which contains all of the line's points.
 *
 * Method: average the unit vectors and renormalize to get a
 * reasonable center direction (this is not necessarily the
 * mathematically optimal cap center, but it doesn't need to be --
 * any fixed center works as long as we then measure the true
 * largest angle from it to any point, which is exactly what the
 * second loop does).  capcos is the *minimum* dot product between
 * the center and any point; since dot product decreases as angle
 * increases, the minimum dot product corresponds to the point
 * farthest from the center, i.e. exactly the half-angle we need.
 *
 * If the points are spread out enough that their vectors largely
 * cancel (e.g. a polyline that wraps most of the way around the
 * globe), the average has near-zero length and "center" stops being
 * a meaningful direction.  In that case we disable culling for this
 * polyline (capcos = -2, see dat.h) rather than risk wrongly
 * skipping a polyline that does have a visible point on screen.
 * That's a correctness fallback, not a bug: the per-point visibility
 * test that already exists in drawcoasts() still renders such a
 * polyline correctly -- we just lose the early-out for it.
 */
static void
computecap(Coastline *c)
{
	int j;
	double sx, sy, sz, len, d, mind;
	Vec3 *v;

	sx = sy = sz = 0;
	for(j = 0; j < c->npts; j++){
		sx += c->vec[j].x;
		sy += c->vec[j].y;
		sz += c->vec[j].z;
	}
	len = sqrt(sx*sx + sy*sy + sz*sz);
	if(len < 1e-9){
		c->center.x = c->center.y = c->center.z = 0;
		c->capcos = -2;
		return;
	}
	c->center.x = sx / len;
	c->center.y = sy / len;
	c->center.z = sz / len;

	mind = 1;
	for(j = 0; j < c->npts; j++){
		v = &c->vec[j];
		d = c->center.x*v->x + c->center.y*v->y + c->center.z*v->z;
		if(d < mind)
			mind = d;
	}
	c->capcos = mind;
}

enum {
	Chunkpts = 256,	/* max points per polyline chunk; see chopcoasts */
};

/*
 * Split long polylines into chunks of at most Chunkpts points.
 * Adjacent chunks share their boundary point, so every segment
 * is still drawn.
 *
 * The bounding-cap cull in drawcoasts() is only as good as the
 * caps are tight: Natural Earth polylines can run for whole
 * continents, and a cap that covers half the sphere never
 * rejects anything, so the cull silently stopped working
 * exactly on the detailed datasets that need it.  Short chunks
 * get small caps, so the far side of the globe is actually
 * skipped again.  Chunks alias the original pts arrays (the
 * data lives for the life of the program; nothing frees it).
 *
 * Must run before computevecs(), which allocates vec[] and
 * computes the cap and step per (post-chop) polyline.
 */
static void
chopcoasts(void)
{
	Coastline *new, *c;
	int i, n, start, len;

	n = 0;
	for(i = 0; i < ncoast; i++){
		if(coasts[i].npts <= Chunkpts)
			n++;
		else
			n += (coasts[i].npts - 1 + Chunkpts - 2) / (Chunkpts - 1);
	}
	new = malloc(n * sizeof(Coastline));
	if(new == nil)
		sysfatal("malloc: %r");
	n = 0;
	for(i = 0; i < ncoast; i++){
		c = &coasts[i];
		for(start = 0; ; start += Chunkpts - 1){
			len = c->npts - start;
			if(len > Chunkpts)
				len = Chunkpts;
			new[n].pts = c->pts + start;
			new[n].npts = len;
			n++;
			if(start + len >= c->npts)
				break;
		}
	}
	free(coasts);
	coasts = new;
	ncoast = n;
}

/*
 * Mean angular step between consecutive points, in radians.
 * Feeds the LOD stride in drawcoasts(); see dat.h.
 */
static double
meanstep(Coastline *c)
{
	int j;
	double sum, d;

	if(c->npts < 2)
		return 0;
	sum = 0;
	for(j = 1; j < c->npts; j++){
		d = c->vec[j-1].x*c->vec[j].x
		  + c->vec[j-1].y*c->vec[j].y
		  + c->vec[j-1].z*c->vec[j].z;
		if(d > 1)
			d = 1;
		if(d < -1)
			d = -1;
		sum += acos(d);
	}
	return sum / (c->npts - 1);
}

/*
 * Precompute a unit vector for every point of every coastline, plus
 * a bounding cap per coastline (see computecap above).  This is the
 * one-time cost that lets globe.c:
 *   - project each point with a handful of multiply-adds per frame
 *     instead of calling sin/cos/asin/atan2 on every point of every
 *     redraw, and
 *   - reject an entire far-side-of-the-globe polyline with one dot
 *     product instead of projecting each of its points first.
 * Both matter once coast.dat has hundreds of thousands of points;
 * neither is needed at the few-hundred-point scale of the fallback
 * outline, but doing it always keeps the code (and this file) simple.
 */
static void
computevecs(void)
{
	int i, j;
	Coastline *c;

	for(i = 0; i < ncoast; i++){
		c = &coasts[i];
		c->vec = malloc(c->npts * sizeof(Vec3));
		if(c->vec == nil)
			sysfatal("malloc: %r");
		for(j = 0; j < c->npts; j++)
			geo2vec(c->pts[j], &c->vec[j]);
		computecap(c);
		c->step = meanstep(c);
	}
}

void
coastinit(void)
{
	int ok;

	ok = 0;
	if(coastpath != nil){
		/*
		 * the user named this file explicitly (-c); failing
		 * loudly beats silently falling back to different data.
		 */
		if(loadfile(coastpath) != 0)
			sysfatal("cannot load coastline file %s", coastpath);
		ok = 1;
	}
	else if(loadfile("coast.dat") == 0)
		ok = 1;
	else if(loadfile("/lib/radio/coast.dat") == 0)
		ok = 1;
	if(!ok){
		fprint(2, "radioglobe: no coast.dat found, using coarse outline\n");
		usefallback();
	}
	chopcoasts();
	computevecs();
}
