#include <u.h>
#include <libc.h>
#include <draw.h>
#include <bio.h>
#include "dat.h"

/*
 * Coastline data, loaded at runtime from coast.dat.
 *
 * coast.dat is generated by mkcoast from a Natural Earth
 * GeoJSON coastline file.  Format: one polyline per block,
 * introduced by "> N" giving the point count, followed by N
 * lines of "lat lon".  Comments and blank lines are ignored.
 *
 * The file is searched for in, in order:
 *	$coastfile (if set via coastfile())
 *	./coast.dat
 *	/lib/radio/coast.dat
 *
 * If no file is found, a coarse built-in outline is used so
 * the globe still shows something recognizable.
 */

Coastline *coasts;
int ncoast;

static char *coastpath;

/* tiny built-in fallback: rough continent blobs */
static Geo fb_africa[] = {
	{35,0},{32,25},{12,43},{-34,20},{-34,18},{5,-5},{15,-17},{35,-6},{35,0},
};
static Geo fb_eurasia[] = {
	{36,-6},{45,5},{60,10},{70,30},{65,60},{70,90},{70,140},{55,140},
	{40,120},{20,105},{8,77},{25,60},{40,50},{36,-6},
};
static Geo fb_namerica[] = {
	{8,-80},{25,-80},{45,-65},{60,-65},{72,-95},{70,-130},{55,-130},
	{33,-117},{18,-105},{8,-80},
};
static Geo fb_samerica[] = {
	{10,-72},{0,-50},{-23,-44},{-40,-62},{-55,-68},{-40,-73},{-18,-70},
	{0,-80},{10,-72},
};
static Geo fb_australia[] = {
	{-11,132},{-20,148},{-38,146},{-35,118},{-20,114},{-11,132},
};

static struct {
	Geo *pts;
	int npts;
} fallback[] = {
	{fb_africa, nelem(fb_africa)},
	{fb_eurasia, nelem(fb_eurasia)},
	{fb_namerica, nelem(fb_namerica)},
	{fb_samerica, nelem(fb_samerica)},
	{fb_australia, nelem(fb_australia)},
};

void
coastfile(char *path)
{
	coastpath = path;
}

static void
usefallback(void)
{
	int i;

	ncoast = nelem(fallback);
	coasts = malloc(ncoast * sizeof(Coastline));
	if(coasts == nil)
		sysfatal("malloc: %r");
	for(i = 0; i < ncoast; i++){
		coasts[i].pts = fallback[i].pts;
		coasts[i].npts = fallback[i].npts;
	}
}

static int
loadfile(char *path)
{
	Biobuf *b;
	char *ln, *f[2];
	int cap, np, want, nf;
	Coastline *c;
	Geo *pts;

	b = Bopen(path, OREAD);
	if(b == nil)
		return -1;

	coasts = nil;
	ncoast = 0;
	cap = 0;
	c = nil;
	pts = nil;
	np = 0;
	want = 0;

	while((ln = Brdline(b, '\n')) != nil){
		ln[Blinelen(b)-1] = 0;
		while(*ln == ' ' || *ln == '\t')
			ln++;
		if(*ln == '#' || *ln == 0)
			continue;

		if(*ln == '>'){
			/* finish previous polyline */
			if(c != nil)
				c->npts = np;

			ln++;
			want = atoi(ln);
			if(want < 2){
				c = nil;
				pts = nil;
				np = 0;
				continue;
			}
			if(ncoast >= cap){
				cap = cap ? cap*2 : 256;
				coasts = realloc(coasts, cap*sizeof(Coastline));
				if(coasts == nil)
					sysfatal("realloc: %r");
			}
			pts = malloc(want * sizeof(Geo));
			if(pts == nil)
				sysfatal("malloc: %r");
			c = &coasts[ncoast++];
			c->pts = pts;
			c->npts = 0;
			np = 0;
			continue;
		}

		/* a "lat lon" coordinate line */
		if(c == nil || np >= want)
			continue;
		nf = tokenize(ln, f, 2);
		if(nf != 2)
			continue;
		pts[np].lat = atof(f[0]);
		pts[np].lon = atof(f[1]);
		np++;
	}
	if(c != nil)
		c->npts = np;

	Bterm(b);

	if(ncoast == 0)
		return -1;
	return 0;
}

void
coastinit(void)
{
	if(coastpath != nil && loadfile(coastpath) == 0)
		return;
	if(loadfile("coast.dat") == 0)
		return;
	if(loadfile("/lib/radio/coast.dat") == 0)
		return;
	fprint(2, "radioglobe: no coast.dat found, using coarse outline\n");
	usefallback();
}
