#include <u.h>
#include <libc.h>
#include <bio.h>
#include <json.h>

/*
 * mkcoast - convert a Natural Earth coastline GeoJSON file
 * into radioglobe's coast.dat format.
 *
 *	mkcoast < ne_110m_coastline.geojson > coast.dat
 *
 * GeoJSON coastline is a FeatureCollection.  Each feature has
 * a geometry of type LineString (an array of [lon,lat] points)
 * or MultiLineString (an array of LineStrings).  Note the
 * coordinate order is [longitude, latitude] -- the reverse of
 * our internal Geo{lat,lon}.
 *
 * Output: one polyline per block:
 *	> N
 *	lat lon
 *	... (N lines)
 * Blank line between blocks.  Comments start with #.
 */

Biobuf *bout;

static char *
readall(int fd)
{
	char *buf;
	long n, sz, tot;

	sz = 1<<20;
	buf = malloc(sz);
	if(buf == nil)
		sysfatal("malloc: %r");
	tot = 0;
	for(;;){
		if(tot >= sz){
			sz *= 2;
			buf = realloc(buf, sz);
			if(buf == nil)
				sysfatal("realloc: %r");
		}
		n = read(fd, buf+tot, sz-tot);
		if(n < 0)
			sysfatal("read: %r");
		if(n == 0)
			break;
		tot += n;
	}
	buf = realloc(buf, tot+1);
	if(buf == nil)
		sysfatal("realloc: %r");
	buf[tot] = 0;
	return buf;
}

/* count points in a LineString (array of [lon,lat] arrays) */
static int
countline(JSON *line)
{
	JSONEl *e;
	int n;

	if(line == nil || line->t != JSONArray)
		return 0;
	n = 0;
	for(e = line->first; e != nil; e = e->next)
		n++;
	return n;
}

/* emit one LineString: an array of [lon,lat] coordinate pairs */
static void
emitline(JSON *line)
{
	JSONEl *e, *c;
	JSON *pt;
	double lon, lat;
	int n;

	n = countline(line);
	if(n < 2)
		return;

	Bprint(bout, "> %d\n", n);
	for(e = line->first; e != nil; e = e->next){
		pt = e->val;
		if(pt == nil || pt->t != JSONArray)
			continue;
		c = pt->first;
		if(c == nil || c->val == nil || c->val->t != JSONNumber)
			continue;
		lon = c->val->n;
		c = c->next;
		if(c == nil || c->val == nil || c->val->t != JSONNumber)
			continue;
		lat = c->val->n;
		Bprint(bout, "%.4f %.4f\n", lat, lon);
	}
	Bprint(bout, "\n");
}

static void
emitgeom(JSON *geom)
{
	JSON *type, *coords;
	JSONEl *e;
	char *t;

	if(geom == nil || geom->t != JSONObject)
		return;
	type = jsonbyname(geom, "type");
	coords = jsonbyname(geom, "coordinates");
	if(type == nil || coords == nil)
		return;
	t = jsonstr(type);
	if(t == nil)
		return;

	if(strcmp(t, "LineString") == 0){
		emitline(coords);
	}else if(strcmp(t, "MultiLineString") == 0){
		/* coords is an array of LineStrings */
		if(coords->t != JSONArray)
			return;
		for(e = coords->first; e != nil; e = e->next)
			emitline(e->val);
	}
	/* ignore Point/Polygon etc. for a coastline theme */
}

void
main(int argc, char **argv)
{
	char *data;
	JSON *root, *feats, *feat, *geom;
	JSONEl *e;
	int nfeat;

	ARGBEGIN{
	default:
		fprint(2, "usage: %s < coastline.geojson > coast.dat\n", argv0);
		exits("usage");
	}ARGEND
	USED(argc); USED(argv);

	data = readall(0);
	root = jsonparse(data);
	if(root == nil)
		sysfatal("jsonparse: %r");

	bout = Bfdopen(1, OWRITE);
	if(bout == nil)
		sysfatal("Bfdopen: %r");

	Bprint(bout, "# radioglobe coastline data\n");
	Bprint(bout, "# generated by mkcoast from Natural Earth GeoJSON\n");

	nfeat = 0;

	/* a FeatureCollection has a "features" array */
	feats = jsonbyname(root, "features");
	if(feats != nil && feats->t == JSONArray){
		for(e = feats->first; e != nil; e = e->next){
			feat = e->val;
			if(feat == nil || feat->t != JSONObject)
				continue;
			geom = jsonbyname(feat, "geometry");
			emitgeom(geom);
			nfeat++;
		}
	}else{
		/* maybe it's a bare geometry or a single feature */
		geom = jsonbyname(root, "geometry");
		if(geom != nil)
			emitgeom(geom);
		else
			emitgeom(root);
	}

	Bterm(bout);
	jsonfree(root);
	free(data);

	fprint(2, "%s: %d features\n", argv0, nfeat);
	exits(nil);
}
